gen-smtp/gen_smtp

package.exs

Hex is a package manager for Elixir (and Erlang) -- making a Hex package makes it a lot easier to use in Elixir projects.
It'd be great if you could publish it to Hex too -- I could do it, but you probably want to make your own releases.
https://hex.pm/docs/publish

Add package.exs for Hex

---

src/gen_smtp_client.erl

The client crashed when doing plain authentication due too the Username beeing a binary.

Fixes crash when username is a binary.

---

src/smtp_util.erl

Hi,
there is use of deprecated function.
```
$ make compile
==> erlang-smtp-test (compile)
Compiled src/smtp_rfc822_parse.yrl
Compiled src/gen_smtp_server_session.erl
Compiled src/gen_smtp_application.erl
Compiled src/gen_smtp_client.erl
Compiled src/smtp_server_example.erl
Compiled src/binstr.erl
Compiled src/gen_smtp_server.erl
src/smtp_util.erl:65: Warning: crypto:md5_mac/2 is deprecated and will be removed in in a future release; use crypto:hmac/3
Compiled src/smtp_util.erl
Compiled src/socket.erl
Compiled src/mimemail.erl
Compiled src/smtp_rfc822_parse.erl
```
I've changed using deprecated function to recommended.
See pull request.
Thanks.

Using of deprected functions from CRYPTO

---

package.exs

For issue #78
I don't have a list of the current active maintainers, so I just added the usernames of people who have merged PRs recently. Please correct me if I'm wrong.
The package is published -- as for publishing new versions, I can do this going on in the future but it would probably be good if someone else had publishing rights too. If any of the maintainers have a registered e-mail address on hex, I can add them as an owner of the `gen_smtp` package on hex.

Update package.exs with contributors and license name

---

src/gen_smtp.app.src

This should fix an issue where the module is being included in the hex package, I noticed this when upgrading to `0.10.0`.

exclude smtp_rfc822_parse.erl from hex package

---

src/gen_smtp_client.erl

I spent a bit too much time debugging a temporary_failure, tls_failed error, only to find out that SSL wasn't started. I found this a bit misleading, hence this suggestion to clarify the cause of the failure. Also, I presume permanent_failure would be the correct error type, but I'm not really familiar with the code base, so there may well be better alternatives.

Throw permanent_failure when TLS fails due to non-started SSL.

---

src/gen_smtp_server.erl
src/gen_smtp_server_session.erl
src/mimemail.erl
src/smtp_util.erl
src/socket.erl

The old -spec(function/arity :: ...) format is not supported in OTP-19, so I have replaces those occurrences with the -spec function(...) notation.

Fix -spec's for OTP-19

---

README.markdown
src/gen_smtp_client.erl
src/socket.erl

`gen_smtp` sends an SSL request even when `tls` is set to `always` and `ssl` is set to `false`. This causes office365's smtp servers to close the connections before we can upgrade to TLS. This change sets the right version while converting the connection to ssl. See #114 for more info.

Set SSL protocol to tlsv1.2 to avoid using incorrect protocol while using TLS

---

src/gen_smtp_client.erl

This solves a bug with slow connections (I didn't create a issue for that).
```
[relay: "my.server.com", port: 587,
hostname: "my.server.com", transport: :smtp,
username: "server@my.server.com", password: "my.server.com", tls: :always,
ssl: false, auth: :if_available, retries: 5]
{:error, :retries_exceeded,
{:network_failure, "my.server.com",
{:error, :timeout}}}
```
(By default it will set 5000)
I have detected the `:socket.connect` has a fixed value for timeout (5000). I need to increase the value, so I think is a good option to be able to set the value via Options.
After this change, and using `timeout: 10000`, with the same example, it works:
```
[relay: "my.server.com", port: 587,
hostname: "my.server.com", transport: :smtp,
username: "server@my.server.com", password: …
```

connect accepts timeout via options, and keeps 5000 as default value

---

src/mimemail.erl

some servers do not set "MIME-Version" header but the content is actually "MIME-Version" : "1.0", so lets try to decode it.
i'm ok with changing `{allow_missing_version, true}` to `{allow_missing_version, false}`. i defaulted to `true` because i think most use cases will benefit from this default

allow missing "MIME-Version" header

---

src/mimemail.erl

Some email senders, notably Yahoo and Amazon SES, send email with a
non-compliant MIME-Version header like:
```
MIME-Version: 1.0
boundary="----=_Part_505990_122814590.1475767204022"
```
This extra data does not seem important, and discarding it does not
hamper parsing the email.
I have reached out to a few vendors to see what purpose the extra data holds and why it was stuck on the MIME-Version header, but I have yet to receive a response.

Relax MIME-Version header checking

---

src/mimemail.erl
test/gen_smtp_util_test.erl

`mimemail:rfc2047_utf8_encode/1` can splite multibyte UTF-8 character to difrent lines.
Example:
Russian word "Информация", `mimemail:rfc2047_utf8_encode/1` converting it into 2 strings
`=?UTF-8?Q?=D0=98=D0=BD=D1=84=D0=BE=D1=80=D0=BC=D0=B0=D1=86=D0=B8=D1?=`
`=?UTF-8?Q?=8F?=`
Last character "и" (`=D1=8F`) splitted, and dont show correctly in mail-readers.

Keep all bytes of one UTF-8 char on same line (no split)

---

.gitignore
src/mimemail.erl
src/smtp_util.erl
src/socket.erl

Special email-name characters like `[`, `@` and `;` were not escaped when combining a name and email address to a rfc822 address.
The specials are defined here:
https://www.w3.org/Protocols/rfc822/3_Lexical.html#z2
```
specials    =  "(" / ")" / "<" / ">" / "@"  ; Must be in quoted-
/  "," / ";" / ":" / "\" / <">  ;  string, to use
/  "." / "[" / "]"              ;  within a word.
```
(This also fixes all tests on OTP 19 - especially some list orders and utf-8 binaries).

Fix a problem where combine_rfc822_addresses/1 improperly escaped certain special characters.

---

src/mimemail.erl

Not an IANA standard and not used for text, but does show up in emails
sent from some clients. Since it is the same as no encoding, we pass it
through unmodified.

Add passthrough for x-binaryenc charset

---

src/mimemail.erl

`io_lib:format('~2.16.0B', [10])` returned `[["0", 65]]` on 20.3, but `"0A"`
on 21.0
Fixes #148

fix io_lib:format match error on Erlang 21.0

---

src/mimemail.erl

Follow up to #149. There was another place with same issue. Thanks to @joefreeman for finding this.

fix another instance of io_lib:format match error on Erlang 21.0

---

src/smtp_util.erl

An alternative to now() is used, that is
{system_time(), unique_integer()}.
Closes #113.

Fix unique_id() to be reasonably unique across node restarts.

---

src/gen_smtp_server_session.erl

Handle `tcp_error` and `ssl_error` messages in the smtp server session process.
Stop the process if any is received.
Fixes #56

Handle tcp_error and ssl_error. 

---

Makefile
rebar.config
src/mimemail.erl
src/socket.erl

* Look for unknown functions and types when dialyzing
* Fix Dialyzer warning triggered by unexported `socket:socket()` type
* Fix Dialyzer warnings on misnamed `ssl:socket()` socket type
* Fix missing wrapping upon skipped `iconv:conv/2` call
* Work around Dialyzer warnings triggered by analysis of eiconv
This is especially useful for library consumers, since some of the found issues would propagate all the way into them and sabotage proper static analysis.

Fix Dialyzer warnings

---

src/gen_smtp_client.erl
src/gen_smtp_server.erl
src/gen_smtp_server_session.erl
src/smtp_socket.erl

This fixes compatibility with OTP-22 which introduces a socket module.
Fixes #168

Rename 'socket' to 'smtp_socket'

---

src/smtp_socket.erl

There were 2 tests faling because of race-condition between user-generated message and inet driver message:
```
1) smtp_socket:ssl_upgrade_test_/0: TCP connection can be upgraded to ssl                                                                                                                                                     
Failure/Error: ?assertMatch({ sslsocket , _ , _ }, NewServerSocket)                                         
expected: = { sslsocket , _ , _ }                                                                                                                                                                                        
got: {inet_async,#Port<0.397>,1,{error,closed}} …
```

Fix ssl upgrade test failures

---

.travis.yml
Makefile
rebar.config
src/smtp_server_example.erl
src/smtp_util.erl

This one just updates travis.yml to more up-to-date erlang versions + adds dialyzer; xref now disabled because of some warnings that will be fixed by #172 and #173. Also some pre-erlang 18 workarounds removed.
I enabled travis for my fork repository, all builds are green https://travis-ci.org/seriyps/gen_smtp/builds/541978093

Require otp18

---

src/gen_smtp_client.erl

Should fix travis build - dialyzer on OTP-18 https://travis-ci.org/gen-smtp/gen_smtp/jobs/556946096#L591

Fix typespec inet:socket_address() doesn't exist on OTP18

---

src/smtp_util.erl

Fixes #152
Errors deriving the FQDN are logged.
Crash if the error is something else than `nxdomain`, as that might hide other problems.

Fallback to FQDN 'localhost' on failure to determine the FQDN of the current machine.

---

src/smtp_socket.erl

As mentioned by @lazedo in https://github.com/gen-smtp/gen_smtp/pull/173/files#r305487660 we are dropping a return value when using ssl:ssl_handshake functions.
This fixes that problem by making the newly introduced ssl_handshake function return same types across OTP versions.

Make ssl_handshake similar across OTP versions

---

src/gen_smtp_server_session.erl
src/smtp_socket.erl

Fixes #182
This softens a race condition when opening/closing sockets during `gen_smtp_server_session` tests.
Also removes a race condition in `smtp_socket` tests.

Soften some race conditions in tests. 

---

src/mimemail.erl

As discussed in #188.
I can also add compatibility function that will internally convert proplist with binary keys to map with atom keys and emit some warning?
Should probably replace space indentation with tab one. For some reason .editorconfig haven't made it for me.

Change mimemail:parameters() to be a map with atom keys

---

src/gen_smtp_client.erl

(cherry picked from commit 813d0258eeac6b9cc4ce47b7a9616ec5f8e43c80)
Fix #194 
Catch errors thrown during send and return them as an error tuple.

Fix a problem where thrown exceptions were not caught in send_it/2

---

src/gen_smtp_client.erl
src/mimemail.erl

The `hssmtp` software appends what seems to be alternative auth methods to the AUTH prompt.
This ignores any extra text after the AUTH prompts for username and password.

Fix a problem with hssmtp auth methods. Fix #203

---

src/gen_smtp_server.erl

For ranch 1.6+ server if we start smtp server as, eg
```erlang
gen_smtp_server:start(Name, Mod, [<..>, {ranch_opts, #{socket_opts => [{ipv6_v6only, true}]}}]).
```
this `socket_opts` parameter in `ranch_opts` will be overwritten, which is not the case for ranch <1.6, and there is no workaround for this.
My usecase was to provide `{ipv6_v6only, true}` option in order to be able to start 2 listeners on all IPs both ipv4 and ipv6 and same port (`0.0.0.0:25` and `[::]:25`).
With this patch it's now possible:
```erlang
> gen_smtp_server:start(
inet6,
smtp_server_example,
[{address, {0,0,0,0,0,0,0,0}},
{port, 2525},
{family, inet6},
{domain, "localhost"},
{ranch_opts, #{socket_opts => [{ipv6_v6only, true}]}}]).    
{ok,<0.295.0>} …
```

Don't overwrite ranch socket_opts (ranch 1.6+)

---

src/gen_smtp_server_session.erl
src/smtp_server_example.erl

Adds `handle_error/3` callback to be able to react to different protocol issues from callback module.
I don't think all possible errors are covered, but more can be added later.
Also, handle tcp_error/ssl_error messages (before this fix they were making the session process forever alive, because were handled by last `handle_info` case that doesn't have timeout).

Add handle_error/3 callback

---

README.markdown
src/gen_smtp_server_session.erl

Fix for https://github.com/gen-smtp/gen_smtp/issues/216.

fix `allow_bare_newlines` documentation

---

.gitignore
.travis.yml
Makefile
src/mimemail.erl

I discovered that `gen_smtp` has quite decent "edocs". Just has some minor issues which crashed the build.
So, fixed those issues and added edoc build to Travis to make sure it will continue to work.

Fix edocs build. Add edoc build to CI

---

.travis.yml
Makefile

Current test coverage is about 82%. I set a threshold a bit lower to have some degree of freedom.
It looks like this in travis logs:
```
===> Performing cover analysis...
|---------------------------|------------|
|                   module  |  coverage  |
|---------------------------|------------|
|          gen_smtp_client  |       80%  |
|      smtp_server_example  |       53%  |
|          gen_smtp_server  |       65%  |
|                smtp_util  |       71%  |
|                 mimemail  |       95%  |
|  gen_smtp_server_session  |       78%  |
|              smtp_socket  |       92%  |
|     gen_smtp_application  |       83%  |
|                   binstr  |       61%  |
|        smtp_rfc822_parse  |       66%  |
|---------------------------|------------|
|                    total …
```

Add test coverage to CI; fail if coverage falls below the limit

---

README.markdown
rebar.config
src/gen_smtp_server.erl
src/gen_smtp_server_session.erl

Again, those who need older Ranch (eg, they use Cowboy 1.x) can use gen_smtp 1.0

Drop support for Ranch below 1.6.0

---

.travis.yml
rebar.config
src/gen_smtp_server_session.erl

OTP-18 apparently is not that much of effort to still support, but I think it just doesn't make sense. OTP-18.3 was released 14 Mar 2016 and is not supported by OTP team anymore.
If someone still needs it, hey can stick to gen_smtp 1.0

Drop support for OTP-18

---

src/mimemail.erl

Encoding to quoted printable was quite slow in cases when calling
string:substr and subsequent lists:concat for inserting soft newline was
used too often. New implementation uses only fast head operations.

Speed up quoted printable encoding

---

src/gen_smtp_server_session.erl

4 independent commits, might be easier to review one by one.
This way we let callback module to decide how to handle such errors. All 3 are actually non-recoverable, as far as I understand, but we didn't crash on `send` historically.
We will stop the session process anyway (callback module can avoid crash logs by returning `{stop, normal, State}` from the `handle_error` function). For `send` error we are changing previous behaviour (used to ignore, now are going to stop).

Smtp server - better error handling

---

README.markdown

Added 'never' to list of valid values for send option auth.
Also changed few commas to dots.
Fixes #231

Updated README section about send option values for auth

---

src/gen_smtp_application.erl
src/mimemail.erl

This pull request fixes two minor warnings that OTP 24 will present after https://github.com/erlang/otp/pull/2995.

Be explicit in our intentions (OTP 24 readiness)

---

.github/workflows/ci.yml
Makefile
rebar.config
src/mimemail.erl
test/prop_mimemail.erl

There are 2 commits: 1st one just fixes #246 (I have choosen, unlike Python, to do QP-encoding of `\r` and `\n`, because otherwise `mimemail` is not able to decode the result).
2nd commit is some "proper" property-based test suite for `mimemail`.
Fix for #246 and test suite were created together, but I decided t split to 2 commits, because they are technically unrelated.
It might be interesting to think about having some "proper" test suite where we compare encoding/decoding of `mimemail` with some other mime codec (eg, some PHP or Python one) to see if they can inter-communicate (mail encoded by Erlang can be read by Python and vice versa), but next time.

Mimemail proper

---

README.markdown

Since Argument 2 of `mimemail:encode/3` requires a map and no longer a list, the README should reflect that

Update README mimemail encode example

---

src/gen_smtp_client.erl

`send_it` expects that `try_smtp_sessions` returns `{ok, Sock}`, but in "restart without TLS" scenario it would return just `Sock`.
I'm quite surprized that Dialyzed did not complain.
This scenario have not been covered by tests, so, a new test was added.

Don't crash SMTP client when TLS is optional and we failed to handshake

---

README.markdown
src/gen_smtp_server.erl
src/gen_smtp_server_session.erl
src/smtp_server_example.erl
test/gen_smtp_server_test.erl

Hello,
I would like to thank the maintainers for the amazing work and propose this PR as my attempt to add support for LMTP. This feature was requested in #196, and is something I find very appropriate, mainly because of the following reasons:
1. LMTP is a very similar protocol to SMTP. In practice it looks more of a variation of SMTP than a completely different protocol... Therefore it makes sense to implement both of them together and avoid code duplication between two different projects and code base.
2. Instead of dealing with the complexity of implementing robust and secure SMTP servers by themselves, a considerable part of developers prefer to deploy other battle-tested solution (with advanced features like anti-spam/anti-virus/grey listing integration like Postfix, OpenSMTPD and …

Add LMTP as an option for the protocol implementation

---

src/mimemail.erl
test/fixtures/message-text-html-attachment.eml

An extra new line was added when a multipart/alternative is encoded inside a multipart/mixed email.
This also adds a fixture and a couple of test for both decoding and encoding.

Remove extra new line on multipart encoding (closes #260)

---

test/prop_mimemail.erl

Some more property-based tests, testing binary attachments this time (used to be plaintext or UTF-8 only before).

mimemail: test binary attachents with proper

---

src/smtp_socket.erl

A lot of new useful options were added to gen_tcp and ssl in the recent
OTP releases, but `smtp_socket` module (that backs gen_smtp_client) currently
only allows a smal set of options and discarded all the not defined in
the whitelist.
We think that it's better to let programmer decide which options they
want to pass - it should e programmer's responsibility if they provide
invalid options.
Especially given that we stopped doing any option filtering for gen_smtp_server after we migrated it to ranch.

gen_smtp_client: stop filtering gen_tcp and ssl options, fixes #271

---

src/gen_smtp_server_session.erl

I noticed that Python's [SMTPLIB](https://docs.python.org/3/library/smtplib.html) sends all verbs in lowercase and gen_smtp fails to recognize `rset\r\n` command.
UPD: while digging deeper, I found https://datatracker.ietf.org/doc/html/rfc4954 and it says that `AUTH xxxx` verb actually makes client/server switch to a SASL subprotocol which uses base64-encoded data exchange. So, it does not make sense to use the same `handle_request`/`parse_request` functions as the ones we use for regular SMTP.
RFC also says that client may interrupt SASL subprotocol by sending `*\r\n`, but I'm not implementing this feature here.

Switch to SASL subprotocol on AUTH command

---

src/gen_smtp.app.src

Hex.pm recommends this, and it helps tools identify exactly which BSD license this project is released under.

Use SPDX ID for licenses

---

.gitignore
src/mimemail.erl
src/smtp_rfc5322_parse.yrl
src/smtp_rfc5322_scan.xrl
src/smtp_rfc822_parse.yrl
src/smtp_util.erl
test/gen_smtp_util_test.erl
test/prop_rfc5322.erl

A more modern and robust parser for address specifiers like this (may appear in To / From / CC etc):
https://datatracker.ietf.org/doc/html/rfc5322#section-3.4
-  `login@domain`
- `Name <login@domain>`
- `Name Surname <login@domain>`
- `Name <login1@domain1>, Name2 <login2@domain2>`
- `group name:login@domain,Name <login2@domain2>;`
Also different versions of escaping of name / login / domain.
It's much more unicode-friendly also.

Replace RFC-822 address-list parser with RFC-5322

---

src/gen_smtp_server_session.erl

https://datatracker.ietf.org/doc/html/rfc6531
It's relatively simple extension that allows SMTP clients send `MAIL FROM: <utf-8 email>` and `RCPT TO: <utf-8 email>`.
I never seen UTF-8 email addresses in a wild so far, but I saw many SMTP servers implementing this extension (including gmail and outlook).

Add support for SMTPUTF8 extension, RFC-6531

---

src/gen_smtp_client.erl

Fix #281 
This removes the test that relies on the presence of the server `smtp.covid19-tracing.ch`

Delete test that relies on an external server.

---

src/gen_smtp_server_session.erl

I unfortunately introduced a bug in https://github.com/gen-smtp/gen_smtp/commit/ecc923e39f2d11af6977ccf0e3238ab6e8c754d7
Turns out, many SMTP senders are sending `MAIL FROM: .... BODY=7bit` when they see `8BITMIME` extension.
see https://datatracker.ietf.org/doc/html/rfc6152#section-2

bugfix: when 8BITMIME extension is enabled, BODY could be "7bit"

---

src/gen_smtp_client.erl

The current client implementation of `gen_smtp_client:deliver/2` always quits the connection to the server when it receives a failure reply in answer to `MAIL FROM`, `RCPT TO`, `DATA`, or the mail body.
Instead, `RSET` could be used to reset (ie cancel) the transaction and keep the connection open.
This PR introduces the option `on_transaction_error` which can be used in a `gen_smtp_client:open/1` call. Possible values are `quit` (the default, resulting in the current behavior) and `reset`.
When `reset` is given for this option, the client will try to issue a `RSET` command after receiving a `4xx` or `5xx` response code in answer to `MAIL FROM`, `RCPT TO` or `DATA` (other unexpected replies will cause a quit), and leave the socket connected if the server replies with `250` to the `RSET` …

Enable using RSET after transaction failures in deliver/2

---

.github/workflows/docs.yml

$default-branch is only available in templates.

Fix CI doc to run on master again

---

.editorconfig
.git-blame-ignore-revs
rebar.config
src/binstr.erl
src/gen_smtp.app.src
src/gen_smtp_client.erl
src/gen_smtp_server.erl
src/gen_smtp_server_session.erl
src/mimemail.erl
src/smtp_server_example.erl
src/smtp_socket.erl
src/smtp_util.erl
test/gen_smtp_server_test.erl
test/gen_smtp_util_test.erl
test/prop_mimemail.erl
test/prop_rfc5322.erl

Just a proof of concept to start the discussion.
Pros:
- we are going to have consistent and modern code style
Cons:
- `git blame` will be confusing by default (unless one does `git config --global blame.ignoreRevsFile .git-blame-ignore-revs`, which is quite common solution)
- already opened PRs and forks would get quite big merge conflicts (could be solved by running `rebar3 fmt` over the fork's source tree). But right now we don't have that many open PRs.

Code formatter

---

src/mimemail.erl

This PR improves Quoted-Printable decoding by removing look-aheads in the remaining binary, and processing the entire body in one go instead of line by line.
This PR also includes a small (unrelated) nano-optimization/correction, replacing a list with a tuple in a case expression and the associated matches.

Improve quoted-printable decoding

---

.editorconfig
.github/workflows/ci.yml
.github/workflows/docs.yml
Makefile
README.md
rebar.config
src/gen_smtp.app.src
src/gen_smtp_server_session.erl

Clean new PR replacing https://github.com/gen-smtp/gen_smtp/pull/290.
---
Additionally this PR removes code meant for < OTP 21.
Additionally this PR introduces format checking in CI.
This part is probably opinionated if task should be allowed to fail
until every maintainer is used to check the format beforehand.
I've added the usage of `ex_doc` & `fmt` to the Makefile as a kind of documentation.
For myself it is not 100% clear how I could make sure I use the latest rebar3 plugin as they are not anywhere pinned.
-> [Upgrading Plugins](https://rebar3.readme.io/docs/using-available-plugins#upgrading-plugins)
This also means I'm not sure how reproducible the CI is regarding the plugins.
All the best.

Generating docs with ExDoc instead of EDoc

---

README.md
rebar.config
src/gen_smtp_client.erl

Hey team!
First of all, I would like to thank you guys for this exceptional work!
Second, I am proposing supporting LMTP in delivering messages.
It would be really useful in cases when it's needed to deliver messages to an LMTP server (ie, Dovecot)
Usage example:
```erlang
Socket = gen_smtp_client:open([{relay, "local-dovecot"}, {protocol, lmtp}])
gen_smtp_client:deliver(Socket, {"whatever@test.com", ["pablo@example.com"],
"Subject: testing\r\nFrom: Andrew Thompson <andrew@hijacked.us>\r\nTo: Some Dude <foo@bar.com>\r\n\r\nThis is the email body"}).
```
I would love to receive suggestions to improve it. This is my first time writing Erlang code.
Thank you

Add LMTP support to the gen_smtp_client

---

README.md
src/smtp_socket.erl
src/smtp_util.erl

As OTP < 21 is not supported anymore we can rely on `ssl:handshake/1` & `ssl:handshake/3`.

Remove legacy OTP support

---

src/mimemail.erl

As pointed out in #310, parameters are supposed to be encoded according to RFC2231, not RFC2047.
The value is first analyzed to decide which representation can/must be used, based on the presence of CTLs, spaces, tspecials, and UTF-8 multibyte characters. Then it is encoded in the selected representation. If the parameter lines become too long (>76 bytes), they are split up according to the continuation scheme described in RFC2231.
In hindsight, getting this right was surprisingly difficult, and therefore a careful review seems to be called for.

RFC2231 header parameter-value encoding

---

README.md

add [hookup.email](https://hookup.email) service to "who is using it" section.

hookup.email is using gen_smtp

---

README.md

`tls_options` seemingly being ignored confused me for quiete a bit until I went through the code and found direct SSL connections actually need a different, not-yet-documented option.
To save others the trouble, here is a doc update :)

Document sockopts

---

rebar.config

Fix the source links, which are currently broken because `rebar3_ex_doc` [assumes the git tags are prefixed with v by default](https://github.com/starbelly/rebar3_ex_doc/pull/46).
Example: https://hexdocs.pm/gen_smtp/1.2.0/readme.html links to: https://github.com/gen-smtp/gen_smtp/blob/v1.2.0/README.md#L1 but it should be: https://github.com/gen-smtp/gen_smtp/blob/1.2.0/README.md#L1.

Fix docs source links

---

.github/workflows/docs.yml
src/gen_smtp_client.erl
src/gen_smtp_server_session.erl

This fixes a problem where the gen_smtp_server crashes if the client sends a QUIT message and immediately hangs up before the "221 Bye" can be send.  This is done by ignoring any send errors.
In the client:  be a bit more subtle when receiving funky multiline replies. Do not immediately crash but just throw an "unexpected_response" exception.
Use OTP 25 for docs build, as ex_doc requires it.

Allow sender to immediately hangup after QUIT message
